# Built with Jekyll 3.2.0

# Setup
title:               Henry
tagline:             'Digital Humanities!'
description:         'Digital Humanities!'
url:                 'https://github.com/hm3293/dh.git'
baseurl:             '/dh'

# About/contact
author:
  name:              Henry Maguire
  url:               none
  email:             hm3293@trevor.org

# Permalinks

permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  texts:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Exclusions from the final site
exclude:
  - optional
  - vendor

# Theme
theme: "ed."


